/*
    prueba-ufinet-autos
    PostgreSQL initialization script

    1. Create the database if it does not exist yet.
    2. Connect to prueba_ufinet_autos.
    3. Run the statements below.
*/

-- CREATE DATABASE prueba_ufinet_autos;

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS cars
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(60) NOT NULL,
    model VARCHAR(60) NOT NULL,
    car_year INTEGER NOT NULL,
    plate_number VARCHAR(20) NOT NULL,
    color VARCHAR(40) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cars_plate_number UNIQUE (plate_number),
    CONSTRAINT ck_cars_car_year CHECK (car_year BETWEEN 1886 AND 2100),
    CONSTRAINT fk_cars_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cars_user_id ON cars (user_id);

-- Optional seed examples:
-- INSERT INTO users (name, email, password)
-- VALUES ('Base User', 'user@example.com', 'change-me');
--
-- INSERT INTO cars (brand, model, car_year, plate_number, color, user_id)
-- VALUES ('Toyota', 'Corolla', 2022, 'ABC123', 'White', 1);
